### ISSUE TITLE
استعمال فرايموورك

### ISSUE THREAD

**Issue by AnasGhrab** [PPTN/www#12]
أش نوّا رايكم في استعمال فرايموورك. اختياري يمشي لهذا : 
https://www.djangoproject.com/

**Comment by slim** [comment]
Pour des raisons de sécurité et de simplicité (le site est hébergé sur plusieurs serveurs) il est préférable de garder une simple page html. Les parties dynamiques du site comme les Communiqués sont hébergés ailleurs (sur blogger)

**Comment by AnasGhrab** [comment]
Justement.. je trouve que l'utilisation de type de blog pas trop valorisante... N'est-il pas préférable d'être indépendant de blogspot.com ?
